// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//edition = "2023";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/wecom/wecom-rpc.proto

package wecom_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RequestUserID string                 `protobuf:"bytes,3,opt,name=requestUserID,proto3" json:"requestUserID,omitempty"`
	AppName       string                 `protobuf:"bytes,4,opt,name=appName,proto3" json:"appName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAO) Reset() {
	*x = MessageAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAO) ProtoMessage() {}

func (x *MessageAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAO.ProtoReflect.Descriptor instead.
func (*MessageAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *MessageAO) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MessageAO) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MessageAO) GetRequestUserID() string {
	if x != nil {
		return x.RequestUserID
	}
	return ""
}

func (x *MessageAO) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type OpenIDListAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenIDList    []string               `protobuf:"bytes,1,rep,name=openIDList,proto3" json:"openIDList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenIDListAO) Reset() {
	*x = OpenIDListAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenIDListAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenIDListAO) ProtoMessage() {}

func (x *OpenIDListAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenIDListAO.ProtoReflect.Descriptor instead.
func (*OpenIDListAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *OpenIDListAO) GetOpenIDList() []string {
	if x != nil {
		return x.OpenIDList
	}
	return nil
}

type ModifyRemarkAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remark        string                 `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	OpenID        string                 `protobuf:"bytes,2,opt,name=openID,proto3" json:"openID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyRemarkAO) Reset() {
	*x = ModifyRemarkAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyRemarkAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRemarkAO) ProtoMessage() {}

func (x *ModifyRemarkAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRemarkAO.ProtoReflect.Descriptor instead.
func (*ModifyRemarkAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyRemarkAO) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ModifyRemarkAO) GetOpenID() string {
	if x != nil {
		return x.OpenID
	}
	return ""
}

type OptionAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Flag          bool                   `protobuf:"varint,4,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionAO) Reset() {
	*x = OptionAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionAO) ProtoMessage() {}

func (x *OptionAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionAO.ProtoReflect.Descriptor instead.
func (*OptionAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *OptionAO) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *OptionAO) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OptionAO) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionAO) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type UserDetailAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	QrCode        string                 `protobuf:"bytes,5,opt,name=qrCode,proto3" json:"qrCode,omitempty"`
	Mobile        string                 `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	BizMail       string                 `protobuf:"bytes,7,opt,name=bizMail,proto3" json:"bizMail,omitempty"`
	Address       string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailAO) Reset() {
	*x = UserDetailAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailAO) ProtoMessage() {}

func (x *UserDetailAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailAO.ProtoReflect.Descriptor instead.
func (*UserDetailAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *UserDetailAO) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserDetailAO) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserDetailAO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetailAO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserDetailAO) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

func (x *UserDetailAO) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserDetailAO) GetBizMail() string {
	if x != nil {
		return x.BizMail
	}
	return ""
}

func (x *UserDetailAO) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetCustomerGroupAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatID        string                 `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerGroupAO) Reset() {
	*x = GetCustomerGroupAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerGroupAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerGroupAO) ProtoMessage() {}

func (x *GetCustomerGroupAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerGroupAO.ProtoReflect.Descriptor instead.
func (*GetCustomerGroupAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerGroupAO) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

func (x *GetCustomerGroupAO) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type FindAccountAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remark        string                 `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TagID         int32                  `protobuf:"varint,4,opt,name=tagID,proto3" json:"tagID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAccountAO) Reset() {
	*x = FindAccountAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAccountAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAccountAO) ProtoMessage() {}

func (x *FindAccountAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAccountAO.ProtoReflect.Descriptor instead.
func (*FindAccountAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *FindAccountAO) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FindAccountAO) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *FindAccountAO) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAccountAO) GetTagID() int32 {
	if x != nil {
		return x.TagID
	}
	return 0
}

type FindCustomerAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remark        string                 `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserID        string                 `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Searcher      string                 `protobuf:"bytes,5,opt,name=searcher,proto3" json:"searcher,omitempty"`
	All           bool                   `protobuf:"varint,6,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCustomerAO) Reset() {
	*x = FindCustomerAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCustomerAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCustomerAO) ProtoMessage() {}

func (x *FindCustomerAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCustomerAO.ProtoReflect.Descriptor instead.
func (*FindCustomerAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *FindCustomerAO) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FindCustomerAO) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *FindCustomerAO) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindCustomerAO) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FindCustomerAO) GetSearcher() string {
	if x != nil {
		return x.Searcher
	}
	return ""
}

func (x *FindCustomerAO) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type FindCustomerGroupAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserID        string                 `protobuf:"bytes,4,opt,name=userID,proto3" json:"userID,omitempty"`
	Searcher      string                 `protobuf:"bytes,5,opt,name=searcher,proto3" json:"searcher,omitempty"`
	All           bool                   `protobuf:"varint,6,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindCustomerGroupAO) Reset() {
	*x = FindCustomerGroupAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindCustomerGroupAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCustomerGroupAO) ProtoMessage() {}

func (x *FindCustomerGroupAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCustomerGroupAO.ProtoReflect.Descriptor instead.
func (*FindCustomerGroupAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *FindCustomerGroupAO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindCustomerGroupAO) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *FindCustomerGroupAO) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindCustomerGroupAO) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *FindCustomerGroupAO) GetSearcher() string {
	if x != nil {
		return x.Searcher
	}
	return ""
}

func (x *FindCustomerGroupAO) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type AddCustomerAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MarkName      string                 `protobuf:"bytes,3,opt,name=markName,proto3" json:"markName,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCustomerAO) Reset() {
	*x = AddCustomerAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCustomerAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerAO) ProtoMessage() {}

func (x *AddCustomerAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerAO.ProtoReflect.Descriptor instead.
func (*AddCustomerAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *AddCustomerAO) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *AddCustomerAO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCustomerAO) GetMarkName() string {
	if x != nil {
		return x.MarkName
	}
	return ""
}

func (x *AddCustomerAO) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UpdateCustomerAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MarkName      string                 `protobuf:"bytes,2,opt,name=markName,proto3" json:"markName,omitempty"`
	OldMarkName   string                 `protobuf:"bytes,3,opt,name=oldMarkName,proto3" json:"oldMarkName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerAO) Reset() {
	*x = UpdateCustomerAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerAO) ProtoMessage() {}

func (x *UpdateCustomerAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerAO.ProtoReflect.Descriptor instead.
func (*UpdateCustomerAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCustomerAO) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UpdateCustomerAO) GetMarkName() string {
	if x != nil {
		return x.MarkName
	}
	return ""
}

func (x *UpdateCustomerAO) GetOldMarkName() string {
	if x != nil {
		return x.OldMarkName
	}
	return ""
}

type GetCustomerInRobotChatAO struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Remark         string                 `protobuf:"bytes,1,opt,name=remark,proto3" json:"remark,omitempty"`
	ExternalUserID string                 `protobuf:"bytes,2,opt,name=externalUserID,proto3" json:"externalUserID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCustomerInRobotChatAO) Reset() {
	*x = GetCustomerInRobotChatAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerInRobotChatAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerInRobotChatAO) ProtoMessage() {}

func (x *GetCustomerInRobotChatAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerInRobotChatAO.ProtoReflect.Descriptor instead.
func (*GetCustomerInRobotChatAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *GetCustomerInRobotChatAO) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GetCustomerInRobotChatAO) GetExternalUserID() string {
	if x != nil {
		return x.ExternalUserID
	}
	return ""
}

type RequestAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *anypb.Any             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataList      []*anypb.Any           `protobuf:"bytes,2,rep,name=dataList,proto3" json:"dataList,omitempty"`
	Map           *anypb.Any             `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	MapList       []*anypb.Any           `protobuf:"bytes,4,rep,name=mapList,proto3" json:"mapList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAO) Reset() {
	*x = RequestAO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAO) ProtoMessage() {}

func (x *RequestAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAO.ProtoReflect.Descriptor instead.
func (*RequestAO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *RequestAO) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RequestAO) GetDataList() []*anypb.Any {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *RequestAO) GetMap() *anypb.Any {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *RequestAO) GetMapList() []*anypb.Any {
	if x != nil {
		return x.MapList
	}
	return nil
}

type ResponseVO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// google.protobuf.Any data = 3;
	Data          *anypb.Any   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DataList      []*anypb.Any `protobuf:"bytes,4,rep,name=dataList,proto3" json:"dataList,omitempty"`
	Map           *anypb.Any   `protobuf:"bytes,5,opt,name=map,proto3" json:"map,omitempty"`
	MapList       []*anypb.Any `protobuf:"bytes,6,rep,name=mapList,proto3" json:"mapList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseVO) Reset() {
	*x = ResponseVO{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVO) ProtoMessage() {}

func (x *ResponseVO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVO.ProtoReflect.Descriptor instead.
func (*ResponseVO) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseVO) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseVO) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResponseVO) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseVO) GetDataList() []*anypb.Any {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *ResponseVO) GetMap() *anypb.Any {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *ResponseVO) GetMapList() []*anypb.Any {
	if x != nil {
		return x.MapList
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wecom_wecom_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_wecom_wecom_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_wecom_wecom_rpc_proto protoreflect.FileDescriptor

const file_proto_wecom_wecom_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/wecom/wecom-rpc.proto\x12\x04wrpc\x1a\x0fproto/any.proto\"}\n" +
	"\tMessageAO\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12$\n" +
	"\rrequestUserID\x18\x03 \x01(\tR\rrequestUserID\x12\x18\n" +
	"\aappName\x18\x04 \x01(\tR\aappName\".\n" +
	"\fOpenIDListAO\x12\x1e\n" +
	"\n" +
	"openIDList\x18\x01 \x03(\tR\n" +
	"openIDList\"@\n" +
	"\x0eModifyRemarkAO\x12\x16\n" +
	"\x06remark\x18\x01 \x01(\tR\x06remark\x12\x16\n" +
	"\x06openID\x18\x02 \x01(\tR\x06openID\"`\n" +
	"\bOptionAO\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x12\n" +
	"\x04flag\x18\x04 \x01(\bR\x04flag\"\xd0\x01\n" +
	"\fUserDetailAO\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06qrCode\x18\x05 \x01(\tR\x06qrCode\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobile\x12\x18\n" +
	"\abizMail\x18\a \x01(\tR\abizMail\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\"J\n" +
	"\x12GetCustomerGroupAO\x12\x16\n" +
	"\x06chatID\x18\x01 \x01(\tR\x06chatID\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\"{\n" +
	"\rFindAccountAO\x12\x16\n" +
	"\x06remark\x18\x01 \x01(\tR\x06remark\x12 \n" +
	"\vcurrentPage\x18\x02 \x01(\x05R\vcurrentPage\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05tagID\x18\x04 \x01(\x05R\x05tagID\"\xac\x01\n" +
	"\x0eFindCustomerAO\x12\x16\n" +
	"\x06remark\x18\x01 \x01(\tR\x06remark\x12 \n" +
	"\vcurrentPage\x18\x02 \x01(\x05R\vcurrentPage\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\x12\x1a\n" +
	"\bsearcher\x18\x05 \x01(\tR\bsearcher\x12\x10\n" +
	"\x03all\x18\x06 \x01(\bR\x03all\"\xad\x01\n" +
	"\x13FindCustomerGroupAO\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vcurrentPage\x18\x02 \x01(\x05R\vcurrentPage\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06userID\x18\x04 \x01(\tR\x06userID\x12\x1a\n" +
	"\bsearcher\x18\x05 \x01(\tR\bsearcher\x12\x10\n" +
	"\x03all\x18\x06 \x01(\bR\x03all\"m\n" +
	"\rAddCustomerAO\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmarkName\x18\x03 \x01(\tR\bmarkName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\"h\n" +
	"\x10UpdateCustomerAO\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bmarkName\x18\x02 \x01(\tR\bmarkName\x12 \n" +
	"\voldMarkName\x18\x03 \x01(\tR\voldMarkName\"Z\n" +
	"\x18GetCustomerInRobotChatAO\x12\x16\n" +
	"\x06remark\x18\x01 \x01(\tR\x06remark\x12&\n" +
	"\x0eexternalUserID\x18\x02 \x01(\tR\x0eexternalUserID\"\xbf\x01\n" +
	"\tRequestAO\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04data\x120\n" +
	"\bdataList\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\bdataList\x12&\n" +
	"\x03map\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03map\x12.\n" +
	"\amapList\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\amapList\"\xe6\x01\n" +
	"\n" +
	"ResponseVO\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x120\n" +
	"\bdataList\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\bdataList\x12&\n" +
	"\x03map\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x03map\x12.\n" +
	"\amapList\x18\x06 \x03(\v2\x14.google.protobuf.AnyR\amapList\"H\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value2\xbf\x1f\n" +
	"\bWecomRPC\x122\n" +
	"\vGetUserList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x125\n" +
	"\x0eGetAllUserList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x122\n" +
	"\vGetUserInfo\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x128\n" +
	"\x0eSaveUserDetail\x12\x12.wrpc.UserDetailAO\x1a\x10.wrpc.ResponseVO\"\x00\x12<\n" +
	"\x15GetUserDetailByUserID\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x128\n" +
	"\x11GetUserDetailList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x122\n" +
	"\vGetRoleList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x126\n" +
	"\x0fGetRoleByUserID\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x128\n" +
	"\x11GetUserByRoleName\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12<\n" +
	"\x10FindCustomerList\x12\x14.wrpc.FindCustomerAO\x1a\x10.wrpc.ResponseVO\"\x00\x12F\n" +
	"\x15FindCustomerGroupList\x12\x19.wrpc.FindCustomerGroupAO\x1a\x10.wrpc.ResponseVO\"\x00\x12F\n" +
	"\x1fFindCustomerCouldBeSelectedList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x126\n" +
	"\vAddCustomer\x12\x13.wrpc.AddCustomerAO\x1a\x10.wrpc.ResponseVO\"\x00\x12B\n" +
	"\x14UpdateCustomerRemark\x12\x16.wrpc.UpdateCustomerAO\x1a\x10.wrpc.ResponseVO\"\x00\x12L\n" +
	"\x16GetCustomerInRobotChat\x12\x1e.wrpc.GetCustomerInRobotChatAO\x1a\x10.wrpc.ResponseVO\"\x00\x12@\n" +
	"\x10GetCustomerGroup\x12\x18.wrpc.GetCustomerGroupAO\x1a\x10.wrpc.ResponseVO\"\x00\x12D\n" +
	"\x14GetCustomerGroupList\x12\x18.wrpc.GetCustomerGroupAO\x1a\x10.wrpc.ResponseVO\"\x00\x12;\n" +
	"\x14GetCustomerGroupChat\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12C\n" +
	"\x1cGetCustomerGroupChatByChatID\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x124\n" +
	"\rFlushCustomer\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x128\n" +
	"\x11SyncCustomerGroup\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x129\n" +
	"\x12FlushCustomerGroup\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12>\n" +
	"\x18QueryCustomerGroupByCond\x12\x0e.wrpc.OptionAO\x1a\x10.wrpc.ResponseVO\"\x00\x122\n" +
	"\vSendTextMsg\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x122\n" +
	"\vSendWarnMsg\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12>\n" +
	"\x13FindAccountUserList\x12\x13.wrpc.FindAccountAO\x1a\x10.wrpc.ResponseVO\"\x00\x126\n" +
	"\x0fSyncAccountUser\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x127\n" +
	"\x10FlushAccountUser\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x129\n" +
	"\x12GetAccountUserList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12H\n" +
	"\x1eGetAccountUserListByOpenIDList\x12\x12.wrpc.OpenIDListAO\x1a\x10.wrpc.ResponseVO\"\x00\x12C\n" +
	"\x17ModifyAccountUserRemark\x12\x14.wrpc.ModifyRemarkAO\x1a\x10.wrpc.ResponseVO\"\x00\x128\n" +
	"\x11GetAccountTagList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12:\n" +
	"\x13GetOauthCallBackURL\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x129\n" +
	"\x12SyncContactWayList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x126\n" +
	"\x0fFlushContactWay\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12:\n" +
	"\x13SendAccountTrackMsg\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x129\n" +
	"\x12SendAccountProcMsg\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x125\n" +
	"\x0eQueryFieldList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x127\n" +
	"\x10FindSupplierList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x123\n" +
	"\fSyncSupplier\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12?\n" +
	"\x18FindBusinessCustomerList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12;\n" +
	"\x14SyncBusinessCustomer\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12=\n" +
	"\x16UpdateBusinessCustomer\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x123\n" +
	"\fFindEnumList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x126\n" +
	"\x0fQueryNameByType\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12:\n" +
	"\x13GetBusinessCustomer\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12@\n" +
	"\x19GetNeedNotifyCustomerList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12:\n" +
	"\x13FindClaimedCustomer\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12>\n" +
	"\x17SaveCustomerPointRecord\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12=\n" +
	"\x16GetCustomerPointRecord\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12>\n" +
	"\x17ListCustomerPointRecord\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x125\n" +
	"\x0eListUserByCond\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12:\n" +
	"\x13JudgeTodayIsWorkday\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12:\n" +
	"\x13QueryIndicatorCount\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12;\n" +
	"\x14QueryIndicatorDetail\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12;\n" +
	"\x14QueryHalfDayLeaveMap\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12=\n" +
	"\x16CalculateUserIndicator\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12;\n" +
	"\x14GenerateReportRecord\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x122\n" +
	"\vSyncAcademy\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x123\n" +
	"\fSyncTraining\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x121\n" +
	"\n" +
	"SyncCourse\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12A\n" +
	"\x1aQueryIndicatorCountInBatch\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12>\n" +
	"\x17QuerySupplierBySpNoList\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x129\n" +
	"\x12SyncInternshipPlan\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x125\n" +
	"\x0eUpdateSupplier\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x121\n" +
	"\n" +
	"UpdateUser\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00\x12;\n" +
	"\x14QueryDataInTimeScope\x12\x0f.wrpc.RequestAO\x1a\x10.wrpc.ResponseVO\"\x00B\x1eZ\x1cgithub.com/iznilul/wecom_rpcb\x06proto3"

var (
	file_proto_wecom_wecom_rpc_proto_rawDescOnce sync.Once
	file_proto_wecom_wecom_rpc_proto_rawDescData []byte
)

func file_proto_wecom_wecom_rpc_proto_rawDescGZIP() []byte {
	file_proto_wecom_wecom_rpc_proto_rawDescOnce.Do(func() {
		file_proto_wecom_wecom_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wecom_wecom_rpc_proto_rawDesc), len(file_proto_wecom_wecom_rpc_proto_rawDesc)))
	})
	return file_proto_wecom_wecom_rpc_proto_rawDescData
}

var file_proto_wecom_wecom_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_wecom_wecom_rpc_proto_goTypes = []any{
	(*MessageAO)(nil),                // 0: wrpc.MessageAO
	(*OpenIDListAO)(nil),             // 1: wrpc.OpenIDListAO
	(*ModifyRemarkAO)(nil),           // 2: wrpc.ModifyRemarkAO
	(*OptionAO)(nil),                 // 3: wrpc.OptionAO
	(*UserDetailAO)(nil),             // 4: wrpc.UserDetailAO
	(*GetCustomerGroupAO)(nil),       // 5: wrpc.GetCustomerGroupAO
	(*FindAccountAO)(nil),            // 6: wrpc.FindAccountAO
	(*FindCustomerAO)(nil),           // 7: wrpc.FindCustomerAO
	(*FindCustomerGroupAO)(nil),      // 8: wrpc.FindCustomerGroupAO
	(*AddCustomerAO)(nil),            // 9: wrpc.AddCustomerAO
	(*UpdateCustomerAO)(nil),         // 10: wrpc.UpdateCustomerAO
	(*GetCustomerInRobotChatAO)(nil), // 11: wrpc.GetCustomerInRobotChatAO
	(*RequestAO)(nil),                // 12: wrpc.RequestAO
	(*ResponseVO)(nil),               // 13: wrpc.ResponseVO
	(*KeyValue)(nil),                 // 14: wrpc.KeyValue
	(*anypb.Any)(nil),                // 15: google.protobuf.Any
}
var file_proto_wecom_wecom_rpc_proto_depIdxs = []int32{
	15, // 0: wrpc.RequestAO.data:type_name -> google.protobuf.Any
	15, // 1: wrpc.RequestAO.dataList:type_name -> google.protobuf.Any
	15, // 2: wrpc.RequestAO.map:type_name -> google.protobuf.Any
	15, // 3: wrpc.RequestAO.mapList:type_name -> google.protobuf.Any
	15, // 4: wrpc.ResponseVO.data:type_name -> google.protobuf.Any
	15, // 5: wrpc.ResponseVO.dataList:type_name -> google.protobuf.Any
	15, // 6: wrpc.ResponseVO.map:type_name -> google.protobuf.Any
	15, // 7: wrpc.ResponseVO.mapList:type_name -> google.protobuf.Any
	15, // 8: wrpc.KeyValue.value:type_name -> google.protobuf.Any
	12, // 9: wrpc.WecomRPC.GetUserList:input_type -> wrpc.RequestAO
	12, // 10: wrpc.WecomRPC.GetAllUserList:input_type -> wrpc.RequestAO
	12, // 11: wrpc.WecomRPC.GetUserInfo:input_type -> wrpc.RequestAO
	4,  // 12: wrpc.WecomRPC.SaveUserDetail:input_type -> wrpc.UserDetailAO
	12, // 13: wrpc.WecomRPC.GetUserDetailByUserID:input_type -> wrpc.RequestAO
	12, // 14: wrpc.WecomRPC.GetUserDetailList:input_type -> wrpc.RequestAO
	12, // 15: wrpc.WecomRPC.GetRoleList:input_type -> wrpc.RequestAO
	12, // 16: wrpc.WecomRPC.GetRoleByUserID:input_type -> wrpc.RequestAO
	12, // 17: wrpc.WecomRPC.GetUserByRoleName:input_type -> wrpc.RequestAO
	7,  // 18: wrpc.WecomRPC.FindCustomerList:input_type -> wrpc.FindCustomerAO
	8,  // 19: wrpc.WecomRPC.FindCustomerGroupList:input_type -> wrpc.FindCustomerGroupAO
	12, // 20: wrpc.WecomRPC.FindCustomerCouldBeSelectedList:input_type -> wrpc.RequestAO
	9,  // 21: wrpc.WecomRPC.AddCustomer:input_type -> wrpc.AddCustomerAO
	10, // 22: wrpc.WecomRPC.UpdateCustomerRemark:input_type -> wrpc.UpdateCustomerAO
	11, // 23: wrpc.WecomRPC.GetCustomerInRobotChat:input_type -> wrpc.GetCustomerInRobotChatAO
	5,  // 24: wrpc.WecomRPC.GetCustomerGroup:input_type -> wrpc.GetCustomerGroupAO
	5,  // 25: wrpc.WecomRPC.GetCustomerGroupList:input_type -> wrpc.GetCustomerGroupAO
	12, // 26: wrpc.WecomRPC.GetCustomerGroupChat:input_type -> wrpc.RequestAO
	12, // 27: wrpc.WecomRPC.GetCustomerGroupChatByChatID:input_type -> wrpc.RequestAO
	12, // 28: wrpc.WecomRPC.FlushCustomer:input_type -> wrpc.RequestAO
	12, // 29: wrpc.WecomRPC.SyncCustomerGroup:input_type -> wrpc.RequestAO
	12, // 30: wrpc.WecomRPC.FlushCustomerGroup:input_type -> wrpc.RequestAO
	3,  // 31: wrpc.WecomRPC.QueryCustomerGroupByCond:input_type -> wrpc.OptionAO
	12, // 32: wrpc.WecomRPC.SendTextMsg:input_type -> wrpc.RequestAO
	12, // 33: wrpc.WecomRPC.SendWarnMsg:input_type -> wrpc.RequestAO
	6,  // 34: wrpc.WecomRPC.FindAccountUserList:input_type -> wrpc.FindAccountAO
	12, // 35: wrpc.WecomRPC.SyncAccountUser:input_type -> wrpc.RequestAO
	12, // 36: wrpc.WecomRPC.FlushAccountUser:input_type -> wrpc.RequestAO
	12, // 37: wrpc.WecomRPC.GetAccountUserList:input_type -> wrpc.RequestAO
	1,  // 38: wrpc.WecomRPC.GetAccountUserListByOpenIDList:input_type -> wrpc.OpenIDListAO
	2,  // 39: wrpc.WecomRPC.ModifyAccountUserRemark:input_type -> wrpc.ModifyRemarkAO
	12, // 40: wrpc.WecomRPC.GetAccountTagList:input_type -> wrpc.RequestAO
	12, // 41: wrpc.WecomRPC.GetOauthCallBackURL:input_type -> wrpc.RequestAO
	12, // 42: wrpc.WecomRPC.SyncContactWayList:input_type -> wrpc.RequestAO
	12, // 43: wrpc.WecomRPC.FlushContactWay:input_type -> wrpc.RequestAO
	12, // 44: wrpc.WecomRPC.SendAccountTrackMsg:input_type -> wrpc.RequestAO
	12, // 45: wrpc.WecomRPC.SendAccountProcMsg:input_type -> wrpc.RequestAO
	12, // 46: wrpc.WecomRPC.QueryFieldList:input_type -> wrpc.RequestAO
	12, // 47: wrpc.WecomRPC.FindSupplierList:input_type -> wrpc.RequestAO
	12, // 48: wrpc.WecomRPC.SyncSupplier:input_type -> wrpc.RequestAO
	12, // 49: wrpc.WecomRPC.FindBusinessCustomerList:input_type -> wrpc.RequestAO
	12, // 50: wrpc.WecomRPC.SyncBusinessCustomer:input_type -> wrpc.RequestAO
	12, // 51: wrpc.WecomRPC.UpdateBusinessCustomer:input_type -> wrpc.RequestAO
	12, // 52: wrpc.WecomRPC.FindEnumList:input_type -> wrpc.RequestAO
	12, // 53: wrpc.WecomRPC.QueryNameByType:input_type -> wrpc.RequestAO
	12, // 54: wrpc.WecomRPC.GetBusinessCustomer:input_type -> wrpc.RequestAO
	12, // 55: wrpc.WecomRPC.GetNeedNotifyCustomerList:input_type -> wrpc.RequestAO
	12, // 56: wrpc.WecomRPC.FindClaimedCustomer:input_type -> wrpc.RequestAO
	12, // 57: wrpc.WecomRPC.SaveCustomerPointRecord:input_type -> wrpc.RequestAO
	12, // 58: wrpc.WecomRPC.GetCustomerPointRecord:input_type -> wrpc.RequestAO
	12, // 59: wrpc.WecomRPC.ListCustomerPointRecord:input_type -> wrpc.RequestAO
	12, // 60: wrpc.WecomRPC.ListUserByCond:input_type -> wrpc.RequestAO
	12, // 61: wrpc.WecomRPC.JudgeTodayIsWorkday:input_type -> wrpc.RequestAO
	12, // 62: wrpc.WecomRPC.QueryIndicatorCount:input_type -> wrpc.RequestAO
	12, // 63: wrpc.WecomRPC.QueryIndicatorDetail:input_type -> wrpc.RequestAO
	12, // 64: wrpc.WecomRPC.QueryHalfDayLeaveMap:input_type -> wrpc.RequestAO
	12, // 65: wrpc.WecomRPC.CalculateUserIndicator:input_type -> wrpc.RequestAO
	12, // 66: wrpc.WecomRPC.GenerateReportRecord:input_type -> wrpc.RequestAO
	12, // 67: wrpc.WecomRPC.SyncAcademy:input_type -> wrpc.RequestAO
	12, // 68: wrpc.WecomRPC.SyncTraining:input_type -> wrpc.RequestAO
	12, // 69: wrpc.WecomRPC.SyncCourse:input_type -> wrpc.RequestAO
	12, // 70: wrpc.WecomRPC.QueryIndicatorCountInBatch:input_type -> wrpc.RequestAO
	12, // 71: wrpc.WecomRPC.QuerySupplierBySpNoList:input_type -> wrpc.RequestAO
	12, // 72: wrpc.WecomRPC.SyncInternshipPlan:input_type -> wrpc.RequestAO
	12, // 73: wrpc.WecomRPC.UpdateSupplier:input_type -> wrpc.RequestAO
	12, // 74: wrpc.WecomRPC.UpdateUser:input_type -> wrpc.RequestAO
	12, // 75: wrpc.WecomRPC.QueryDataInTimeScope:input_type -> wrpc.RequestAO
	13, // 76: wrpc.WecomRPC.GetUserList:output_type -> wrpc.ResponseVO
	13, // 77: wrpc.WecomRPC.GetAllUserList:output_type -> wrpc.ResponseVO
	13, // 78: wrpc.WecomRPC.GetUserInfo:output_type -> wrpc.ResponseVO
	13, // 79: wrpc.WecomRPC.SaveUserDetail:output_type -> wrpc.ResponseVO
	13, // 80: wrpc.WecomRPC.GetUserDetailByUserID:output_type -> wrpc.ResponseVO
	13, // 81: wrpc.WecomRPC.GetUserDetailList:output_type -> wrpc.ResponseVO
	13, // 82: wrpc.WecomRPC.GetRoleList:output_type -> wrpc.ResponseVO
	13, // 83: wrpc.WecomRPC.GetRoleByUserID:output_type -> wrpc.ResponseVO
	13, // 84: wrpc.WecomRPC.GetUserByRoleName:output_type -> wrpc.ResponseVO
	13, // 85: wrpc.WecomRPC.FindCustomerList:output_type -> wrpc.ResponseVO
	13, // 86: wrpc.WecomRPC.FindCustomerGroupList:output_type -> wrpc.ResponseVO
	13, // 87: wrpc.WecomRPC.FindCustomerCouldBeSelectedList:output_type -> wrpc.ResponseVO
	13, // 88: wrpc.WecomRPC.AddCustomer:output_type -> wrpc.ResponseVO
	13, // 89: wrpc.WecomRPC.UpdateCustomerRemark:output_type -> wrpc.ResponseVO
	13, // 90: wrpc.WecomRPC.GetCustomerInRobotChat:output_type -> wrpc.ResponseVO
	13, // 91: wrpc.WecomRPC.GetCustomerGroup:output_type -> wrpc.ResponseVO
	13, // 92: wrpc.WecomRPC.GetCustomerGroupList:output_type -> wrpc.ResponseVO
	13, // 93: wrpc.WecomRPC.GetCustomerGroupChat:output_type -> wrpc.ResponseVO
	13, // 94: wrpc.WecomRPC.GetCustomerGroupChatByChatID:output_type -> wrpc.ResponseVO
	13, // 95: wrpc.WecomRPC.FlushCustomer:output_type -> wrpc.ResponseVO
	13, // 96: wrpc.WecomRPC.SyncCustomerGroup:output_type -> wrpc.ResponseVO
	13, // 97: wrpc.WecomRPC.FlushCustomerGroup:output_type -> wrpc.ResponseVO
	13, // 98: wrpc.WecomRPC.QueryCustomerGroupByCond:output_type -> wrpc.ResponseVO
	13, // 99: wrpc.WecomRPC.SendTextMsg:output_type -> wrpc.ResponseVO
	13, // 100: wrpc.WecomRPC.SendWarnMsg:output_type -> wrpc.ResponseVO
	13, // 101: wrpc.WecomRPC.FindAccountUserList:output_type -> wrpc.ResponseVO
	13, // 102: wrpc.WecomRPC.SyncAccountUser:output_type -> wrpc.ResponseVO
	13, // 103: wrpc.WecomRPC.FlushAccountUser:output_type -> wrpc.ResponseVO
	13, // 104: wrpc.WecomRPC.GetAccountUserList:output_type -> wrpc.ResponseVO
	13, // 105: wrpc.WecomRPC.GetAccountUserListByOpenIDList:output_type -> wrpc.ResponseVO
	13, // 106: wrpc.WecomRPC.ModifyAccountUserRemark:output_type -> wrpc.ResponseVO
	13, // 107: wrpc.WecomRPC.GetAccountTagList:output_type -> wrpc.ResponseVO
	13, // 108: wrpc.WecomRPC.GetOauthCallBackURL:output_type -> wrpc.ResponseVO
	13, // 109: wrpc.WecomRPC.SyncContactWayList:output_type -> wrpc.ResponseVO
	13, // 110: wrpc.WecomRPC.FlushContactWay:output_type -> wrpc.ResponseVO
	13, // 111: wrpc.WecomRPC.SendAccountTrackMsg:output_type -> wrpc.ResponseVO
	13, // 112: wrpc.WecomRPC.SendAccountProcMsg:output_type -> wrpc.ResponseVO
	13, // 113: wrpc.WecomRPC.QueryFieldList:output_type -> wrpc.ResponseVO
	13, // 114: wrpc.WecomRPC.FindSupplierList:output_type -> wrpc.ResponseVO
	13, // 115: wrpc.WecomRPC.SyncSupplier:output_type -> wrpc.ResponseVO
	13, // 116: wrpc.WecomRPC.FindBusinessCustomerList:output_type -> wrpc.ResponseVO
	13, // 117: wrpc.WecomRPC.SyncBusinessCustomer:output_type -> wrpc.ResponseVO
	13, // 118: wrpc.WecomRPC.UpdateBusinessCustomer:output_type -> wrpc.ResponseVO
	13, // 119: wrpc.WecomRPC.FindEnumList:output_type -> wrpc.ResponseVO
	13, // 120: wrpc.WecomRPC.QueryNameByType:output_type -> wrpc.ResponseVO
	13, // 121: wrpc.WecomRPC.GetBusinessCustomer:output_type -> wrpc.ResponseVO
	13, // 122: wrpc.WecomRPC.GetNeedNotifyCustomerList:output_type -> wrpc.ResponseVO
	13, // 123: wrpc.WecomRPC.FindClaimedCustomer:output_type -> wrpc.ResponseVO
	13, // 124: wrpc.WecomRPC.SaveCustomerPointRecord:output_type -> wrpc.ResponseVO
	13, // 125: wrpc.WecomRPC.GetCustomerPointRecord:output_type -> wrpc.ResponseVO
	13, // 126: wrpc.WecomRPC.ListCustomerPointRecord:output_type -> wrpc.ResponseVO
	13, // 127: wrpc.WecomRPC.ListUserByCond:output_type -> wrpc.ResponseVO
	13, // 128: wrpc.WecomRPC.JudgeTodayIsWorkday:output_type -> wrpc.ResponseVO
	13, // 129: wrpc.WecomRPC.QueryIndicatorCount:output_type -> wrpc.ResponseVO
	13, // 130: wrpc.WecomRPC.QueryIndicatorDetail:output_type -> wrpc.ResponseVO
	13, // 131: wrpc.WecomRPC.QueryHalfDayLeaveMap:output_type -> wrpc.ResponseVO
	13, // 132: wrpc.WecomRPC.CalculateUserIndicator:output_type -> wrpc.ResponseVO
	13, // 133: wrpc.WecomRPC.GenerateReportRecord:output_type -> wrpc.ResponseVO
	13, // 134: wrpc.WecomRPC.SyncAcademy:output_type -> wrpc.ResponseVO
	13, // 135: wrpc.WecomRPC.SyncTraining:output_type -> wrpc.ResponseVO
	13, // 136: wrpc.WecomRPC.SyncCourse:output_type -> wrpc.ResponseVO
	13, // 137: wrpc.WecomRPC.QueryIndicatorCountInBatch:output_type -> wrpc.ResponseVO
	13, // 138: wrpc.WecomRPC.QuerySupplierBySpNoList:output_type -> wrpc.ResponseVO
	13, // 139: wrpc.WecomRPC.SyncInternshipPlan:output_type -> wrpc.ResponseVO
	13, // 140: wrpc.WecomRPC.UpdateSupplier:output_type -> wrpc.ResponseVO
	13, // 141: wrpc.WecomRPC.UpdateUser:output_type -> wrpc.ResponseVO
	13, // 142: wrpc.WecomRPC.QueryDataInTimeScope:output_type -> wrpc.ResponseVO
	76, // [76:143] is the sub-list for method output_type
	9,  // [9:76] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_wecom_wecom_rpc_proto_init() }
func file_proto_wecom_wecom_rpc_proto_init() {
	if File_proto_wecom_wecom_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wecom_wecom_rpc_proto_rawDesc), len(file_proto_wecom_wecom_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wecom_wecom_rpc_proto_goTypes,
		DependencyIndexes: file_proto_wecom_wecom_rpc_proto_depIdxs,
		MessageInfos:      file_proto_wecom_wecom_rpc_proto_msgTypes,
	}.Build()
	File_proto_wecom_wecom_rpc_proto = out.File
	file_proto_wecom_wecom_rpc_proto_goTypes = nil
	file_proto_wecom_wecom_rpc_proto_depIdxs = nil
}
