// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//edition = "2023";

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/booking/booking-rpc.proto

package booking_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseVO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DataList      []*anypb.Any           `protobuf:"bytes,4,rep,name=dataList,proto3" json:"dataList,omitempty"`
	Map           *anypb.Any             `protobuf:"bytes,5,opt,name=map,proto3" json:"map,omitempty"`
	MapList       []*anypb.Any           `protobuf:"bytes,6,rep,name=mapList,proto3" json:"mapList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseVO) Reset() {
	*x = ResponseVO{}
	mi := &file_proto_booking_booking_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseVO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseVO) ProtoMessage() {}

func (x *ResponseVO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseVO.ProtoReflect.Descriptor instead.
func (*ResponseVO) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseVO) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseVO) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResponseVO) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ResponseVO) GetDataList() []*anypb.Any {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *ResponseVO) GetMap() *anypb.Any {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *ResponseVO) GetMapList() []*anypb.Any {
	if x != nil {
		return x.MapList
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_booking_booking_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type RequestAO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *anypb.Any             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataList      []*anypb.Any           `protobuf:"bytes,2,rep,name=dataList,proto3" json:"dataList,omitempty"`
	Map           *anypb.Any             `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	MapList       []*anypb.Any           `protobuf:"bytes,4,rep,name=mapList,proto3" json:"mapList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAO) Reset() {
	*x = RequestAO{}
	mi := &file_proto_booking_booking_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAO) ProtoMessage() {}

func (x *RequestAO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAO.ProtoReflect.Descriptor instead.
func (*RequestAO) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RequestAO) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RequestAO) GetDataList() []*anypb.Any {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *RequestAO) GetMap() *anypb.Any {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *RequestAO) GetMapList() []*anypb.Any {
	if x != nil {
		return x.MapList
	}
	return nil
}

var File_proto_booking_booking_rpc_proto protoreflect.FileDescriptor

const file_proto_booking_booking_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/booking/booking-rpc.proto\x12\x05borpc\x1a\x0fproto/any.proto\"\xe6\x01\n" +
	"\n" +
	"ResponseVO\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x120\n" +
	"\bdataList\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\bdataList\x12&\n" +
	"\x03map\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x03map\x12.\n" +
	"\amapList\x18\x06 \x03(\v2\x14.google.protobuf.AnyR\amapList\"H\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xbf\x01\n" +
	"\tRequestAO\x12(\n" +
	"\x04data\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04data\x120\n" +
	"\bdataList\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\bdataList\x12&\n" +
	"\x03map\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03map\x12.\n" +
	"\amapList\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\amapList2\xf3\x04\n" +
	"\n" +
	"BookingRPC\x125\n" +
	"\fFindMiniUser\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x129\n" +
	"\x10FindMiniUserList\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x12E\n" +
	"\x1cFindMiniUserListByOpenIDList\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x124\n" +
	"\vSendMiniMsg\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x12<\n" +
	"\x13QueryIndicatorCount\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x12=\n" +
	"\x14QueryIndicatorDetail\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x12?\n" +
	"\x16CalculateUserIndicator\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x124\n" +
	"\vGetGiftList\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x12C\n" +
	"\x1aQueryIndicatorCountInBatch\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00\x12=\n" +
	"\x14QueryDataInTimeScope\x12\x10.borpc.RequestAO\x1a\x11.borpc.ResponseVO\"\x00B Z\x1egithub.com/iznilul/booking_rpcb\x06proto3"

var (
	file_proto_booking_booking_rpc_proto_rawDescOnce sync.Once
	file_proto_booking_booking_rpc_proto_rawDescData []byte
)

func file_proto_booking_booking_rpc_proto_rawDescGZIP() []byte {
	file_proto_booking_booking_rpc_proto_rawDescOnce.Do(func() {
		file_proto_booking_booking_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_booking_rpc_proto_rawDesc), len(file_proto_booking_booking_rpc_proto_rawDesc)))
	})
	return file_proto_booking_booking_rpc_proto_rawDescData
}

var file_proto_booking_booking_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_booking_booking_rpc_proto_goTypes = []any{
	(*ResponseVO)(nil), // 0: borpc.ResponseVO
	(*KeyValue)(nil),   // 1: borpc.KeyValue
	(*RequestAO)(nil),  // 2: borpc.RequestAO
	(*anypb.Any)(nil),  // 3: google.protobuf.Any
}
var file_proto_booking_booking_rpc_proto_depIdxs = []int32{
	3,  // 0: borpc.ResponseVO.data:type_name -> google.protobuf.Any
	3,  // 1: borpc.ResponseVO.dataList:type_name -> google.protobuf.Any
	3,  // 2: borpc.ResponseVO.map:type_name -> google.protobuf.Any
	3,  // 3: borpc.ResponseVO.mapList:type_name -> google.protobuf.Any
	3,  // 4: borpc.KeyValue.value:type_name -> google.protobuf.Any
	3,  // 5: borpc.RequestAO.data:type_name -> google.protobuf.Any
	3,  // 6: borpc.RequestAO.dataList:type_name -> google.protobuf.Any
	3,  // 7: borpc.RequestAO.map:type_name -> google.protobuf.Any
	3,  // 8: borpc.RequestAO.mapList:type_name -> google.protobuf.Any
	2,  // 9: borpc.BookingRPC.FindMiniUser:input_type -> borpc.RequestAO
	2,  // 10: borpc.BookingRPC.FindMiniUserList:input_type -> borpc.RequestAO
	2,  // 11: borpc.BookingRPC.FindMiniUserListByOpenIDList:input_type -> borpc.RequestAO
	2,  // 12: borpc.BookingRPC.SendMiniMsg:input_type -> borpc.RequestAO
	2,  // 13: borpc.BookingRPC.QueryIndicatorCount:input_type -> borpc.RequestAO
	2,  // 14: borpc.BookingRPC.QueryIndicatorDetail:input_type -> borpc.RequestAO
	2,  // 15: borpc.BookingRPC.CalculateUserIndicator:input_type -> borpc.RequestAO
	2,  // 16: borpc.BookingRPC.GetGiftList:input_type -> borpc.RequestAO
	2,  // 17: borpc.BookingRPC.QueryIndicatorCountInBatch:input_type -> borpc.RequestAO
	2,  // 18: borpc.BookingRPC.QueryDataInTimeScope:input_type -> borpc.RequestAO
	0,  // 19: borpc.BookingRPC.FindMiniUser:output_type -> borpc.ResponseVO
	0,  // 20: borpc.BookingRPC.FindMiniUserList:output_type -> borpc.ResponseVO
	0,  // 21: borpc.BookingRPC.FindMiniUserListByOpenIDList:output_type -> borpc.ResponseVO
	0,  // 22: borpc.BookingRPC.SendMiniMsg:output_type -> borpc.ResponseVO
	0,  // 23: borpc.BookingRPC.QueryIndicatorCount:output_type -> borpc.ResponseVO
	0,  // 24: borpc.BookingRPC.QueryIndicatorDetail:output_type -> borpc.ResponseVO
	0,  // 25: borpc.BookingRPC.CalculateUserIndicator:output_type -> borpc.ResponseVO
	0,  // 26: borpc.BookingRPC.GetGiftList:output_type -> borpc.ResponseVO
	0,  // 27: borpc.BookingRPC.QueryIndicatorCountInBatch:output_type -> borpc.ResponseVO
	0,  // 28: borpc.BookingRPC.QueryDataInTimeScope:output_type -> borpc.ResponseVO
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_booking_booking_rpc_proto_init() }
func file_proto_booking_booking_rpc_proto_init() {
	if File_proto_booking_booking_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_booking_rpc_proto_rawDesc), len(file_proto_booking_booking_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_booking_rpc_proto_goTypes,
		DependencyIndexes: file_proto_booking_booking_rpc_proto_depIdxs,
		MessageInfos:      file_proto_booking_booking_rpc_proto_msgTypes,
	}.Build()
	File_proto_booking_booking_rpc_proto = out.File
	file_proto_booking_booking_rpc_proto_goTypes = nil
	file_proto_booking_booking_rpc_proto_depIdxs = nil
}
